In [2]:
import numpy as np

In [3]:
my_matrix=[[5,10],[20,30]]

In [4]:
my_matrix[0]

[5, 10]

In [5]:
#matrix yapısı row * column

In [6]:
numpy_matrix =  np.array([[5,10],[15,20]])

In [7]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [8]:
numpy_matrix[1][0]

np.int64(15)

In [9]:
numpy_matrix.sum()

np.int64(50)

In [10]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np.zeros((3,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
np.random.random((3,4))

array([[0.75231726, 0.95483567, 0.86750268, 0.88082939],
       [0.15725361, 0.38271371, 0.7209467 , 0.16969241],
       [0.14523525, 0.93698226, 0.64842702, 0.07141136]])

In [13]:
#matrix aritmetiği

In [14]:
array1=np.array([[25,35],[50,60]])

In [15]:
array2 = np.array([[55,65],[35,65]])

In [16]:
array1 + array2

array([[ 80, 100],
       [ 85, 125]])

In [17]:
array1

array([[25, 35],
       [50, 60]])

In [18]:
array3 =np.array([[50,60]])

In [20]:
array3

array([[50, 60]])

In [21]:
array1 + array3

array([[ 75,  95],
       [100, 120]])

In [22]:
array4=np.array([[10,20,30,40,]])

In [24]:
array4 + array1
#işlem yapamaz

ValueError: operands could not be broadcast together with shapes (1,4) (2,2) 

In [26]:
array1.shape

(2, 2)

In [27]:
array5  = np.array([[10],[20]])

In [28]:
array5

array([[10],
       [20]])

In [29]:
array5.shape

(2, 1)

In [30]:
array1 + array5

array([[35, 45],
       [70, 80]])

In [31]:
#matrix  çarpma işlemi

In [32]:
array1 * array2

array([[1375, 2275],
       [1750, 3900]])

In [33]:
#dot product

In [34]:
new_matrix = np.array([[10,20,30,]])

In [35]:
new_matrix

array([[10, 20, 30]])

In [36]:
new_matrix.shape

(1, 3)

In [37]:
new_matrix2=np.array([[2,3],[2,3],[2,3]])

In [38]:
new_matrix2

array([[2, 3],
       [2, 3],
       [2, 3]])

In [39]:
new_matrix2.shape

(3, 2)

In [40]:
#new_matrix * new_matrix2

In [42]:
result=new_matrix.dot(new_matrix2)

In [43]:
result

array([[120, 180]])

In [44]:
result.shape

(1, 2)